// M_Body as a ShaderGraph — port of shaders/materials/body.ts (仿深空之眼 "M_Body").
// Toon + warm rim + rim1/rim2 stack mixed 50/50 against a Lit layer with
// noise-bumped normal. The hand port's local ramp_ease is ramp_cardinal (identical
// smoothstep form); the Mapping node's zero loc/rot folds to a scale multiply.

import type { ShaderGraph } from "../schema"

export const BODY_GRAPH: ShaderGraph = {
  version: 1,
  name: "Body",
  tags: ["body"],
  nodes: [
    { id: "tex", type: "texture" },
    // Base colour: the texture times the PMX material's diffuse. MMD authors
    // tint per MATERIAL rather than per texel — an eyebrow sharing the face
    // atlas is painted once and coloured here — so the diffuse belongs in the
    // base of every look.
    { id: "mat_diffuse", type: "material_diffuse" },
    { id: "tex_base", type: "mix/multiply", inputs: { fac: 1.0 } },
    { id: "geo", type: "geometry" },
    { id: "str", type: "lambert" },
    { id: "toon", type: "ramp_cardinal", inputs: { pos0: 0.2466, pos1: 0.3466 } },
    { id: "shadow_tint", type: "hue_sat", inputs: { hue: 0.5, saturation: 2.0, value: 0.3499999940395355, fac: 1.0 } },
    { id: "lit_tint", type: "hue_sat", inputs: { hue: 0.5, saturation: 1.5, value: 1.0, fac: 1.0 } },
    { id: "toon_color", type: "mix/blend" },
    { id: "bc", type: "bright_contrast", inputs: { bright: 0.1, contrast: 0.2 } },
    { id: "emission3", type: "vector_math/scale", inputs: { scale: 3.2 } },
    { id: "warm_add", type: "math/add", inputs: { b: 0.5 } },
    { id: "warm_clamp", type: "math/clamp01" },
    {
      id: "warm_ramp",
      type: "ramp_cardinal",
      inputs: {
        pos0: 0.2409,
        color0: [0.2426, 0.068, 0.0588, 1.0],
        pos1: 0.4663,
        color1: [0.6677, 0.5024, 0.5126, 1.0],
      },
    },
    { id: "warm_emit", type: "vector_math/scale", inputs: { scale: 0.30000001192092896 } },
    { id: "rim1_fres", type: "fresnel", inputs: { ior: 2.0 } },
    { id: "rim1_lw", type: "layer_weight/facing", inputs: { blend: 0.24000005424022675 } },
    { id: "rim1_str", type: "math/multiply" },
    { id: "rim1", type: "vector_math/scale" },
    { id: "rim1_color", type: "rgb", inputs: { color: [0.984157919883728, 0.6110184788703918, 0.5736401677131653] } },
    { id: "rim2_lw", type: "layer_weight/facing", inputs: { blend: 0.20000000298023224 } },
    { id: "rim2_pow", type: "math/power", inputs: { b: 1.4300000667572021 } },
    { id: "rim2_ramp", type: "ramp_cardinal", inputs: { pos0: 0.0, pos1: 0.5052 } },
    { id: "rim2_mix", type: "mix/blend", inputs: { b: [1.0, 0.4303792119026184, 0.3315804898738861] } },
    { id: "npr_add1", type: "vector_math/add" },
    { id: "npr_stack", type: "vector_math/add" },
    { id: "map", type: "mapping", inputs: { scl: [1.0, 1.0, 1.5] } },
    { id: "noise", type: "tex_noise", inputs: { scale: 1.0 } },
    { id: "noise_ramp", type: "ramp_linear", inputs: { pos0: 0.0, pos1: 1.0 } },
    { id: "bump", type: "bump", inputs: { strength: 0.324644535779953 } },
    {
      id: "principled_base",
      type: "mix/blend",
      inputs: { b: [0.6831911206245422, 0.19474034011363983, 0.13732507824897766] },
    },
    { id: "p_emit", type: "vector_math/scale", inputs: { scale: 0.2 } },
    {
      id: "principled",
      type: "lit",
      inputs: { metallic: 0.0, smoothness: 0.4523 },
    },
    { id: "p_sum", type: "vector_math/add" },
    { id: "mix_shader_001", type: "mix/blend", inputs: { fac: 0.5 } },
  ],
  links: [
    { from: { node: "str", socket: "value" }, to: { node: "toon", socket: "fac" } },
    { from: { node: "tex", socket: "color" }, to: { node: "tex_base", socket: "a" } },
    { from: { node: "mat_diffuse", socket: "color" }, to: { node: "tex_base", socket: "b" } },
    { from: { node: "tex_base", socket: "color" }, to: { node: "shadow_tint", socket: "color" } },
    { from: { node: "tex_base", socket: "color" }, to: { node: "lit_tint", socket: "color" } },
    { from: { node: "toon", socket: "fac_out" }, to: { node: "toon_color", socket: "fac" } },
    { from: { node: "shadow_tint", socket: "color" }, to: { node: "toon_color", socket: "a" } },
    { from: { node: "lit_tint", socket: "color" }, to: { node: "toon_color", socket: "b" } },
    { from: { node: "toon_color", socket: "color" }, to: { node: "bc", socket: "color" } },
    { from: { node: "bc", socket: "color" }, to: { node: "emission3", socket: "a" } },
    { from: { node: "toon", socket: "fac_out" }, to: { node: "warm_add", socket: "a" } },
    { from: { node: "warm_add", socket: "value" }, to: { node: "warm_clamp", socket: "a" } },
    { from: { node: "warm_clamp", socket: "value" }, to: { node: "warm_ramp", socket: "fac" } },
    { from: { node: "warm_ramp", socket: "color" }, to: { node: "warm_emit", socket: "a" } },
    { from: { node: "rim1_fres", socket: "value" }, to: { node: "rim1_str", socket: "a" } },
    { from: { node: "rim1_lw", socket: "value" }, to: { node: "rim1_str", socket: "b" } },
    { from: { node: "rim1_str", socket: "value" }, to: { node: "rim1", socket: "scale" } },
    { from: { node: "rim2_lw", socket: "value" }, to: { node: "rim2_pow", socket: "a" } },
    { from: { node: "rim2_pow", socket: "value" }, to: { node: "rim2_ramp", socket: "fac" } },
    { from: { node: "emission3", socket: "vector" }, to: { node: "rim2_mix", socket: "a" } },
    { from: { node: "rim2_ramp", socket: "fac_out" }, to: { node: "rim2_mix", socket: "fac" } },
    { from: { node: "rim1_color", socket: "color" }, to: { node: "rim1", socket: "a" } },
    { from: { node: "rim1", socket: "vector" }, to: { node: "npr_add1", socket: "a" } },
    { from: { node: "rim2_mix", socket: "color" }, to: { node: "npr_add1", socket: "b" } },
    { from: { node: "npr_add1", socket: "vector" }, to: { node: "npr_stack", socket: "a" } },
    { from: { node: "warm_emit", socket: "vector" }, to: { node: "npr_stack", socket: "b" } },
    { from: { node: "geo", socket: "rest_pos" }, to: { node: "map", socket: "vector" } },
    { from: { node: "map", socket: "vector" }, to: { node: "noise", socket: "vector" } },
    { from: { node: "noise", socket: "value" }, to: { node: "noise_ramp", socket: "fac" } },
    { from: { node: "noise_ramp", socket: "fac_out" }, to: { node: "bump", socket: "height" } },
    { from: { node: "geo", socket: "normal" }, to: { node: "bump", socket: "normal" } },
    { from: { node: "noise_ramp", socket: "fac_out" }, to: { node: "principled_base", socket: "fac" } },
    { from: { node: "bc", socket: "color" }, to: { node: "principled_base", socket: "a" } },
    { from: { node: "bc", socket: "color" }, to: { node: "p_emit", socket: "a" } },
    { from: { node: "principled_base", socket: "color" }, to: { node: "principled", socket: "base_color" } },
    { from: { node: "bump", socket: "vector" }, to: { node: "principled", socket: "normal" } },
    { from: { node: "principled", socket: "color" }, to: { node: "p_sum", socket: "a" } },
    { from: { node: "p_emit", socket: "vector" }, to: { node: "p_sum", socket: "b" } },
    { from: { node: "npr_stack", socket: "vector" }, to: { node: "mix_shader_001", socket: "a" } },
    { from: { node: "p_sum", socket: "vector" }, to: { node: "mix_shader_001", socket: "b" } },
  ],
  output: { node: "mix_shader_001", socket: "color" },
}
